"""initial_schema

Revision ID: 58cb28ebe888
Revises: 
Create Date: 2026-09-15 22:17:53.969013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cb28ebe888'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('role', sa.Enum('USER', 'DRIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_license_number'), ['license_number'], unique=True)

    op.create_table('ambulances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('ambulance_type', sa.Enum('BASIC', 'ADVANCED', 'ICU', 'PATIENT_TRANSPORT', name='ambulancetype'), nullable=False),
    sa.Column('equipment_details', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambulances_ambulance_type'), ['ambulance_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ambulances_vehicle_number'), ['vehicle_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ambulances_verification_status'), ['verification_status'], unique=False)

    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ambulance_id')
    )
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availabilities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availabilities_is_online'), ['is_online'], unique=False)

    op.create_table('emergency_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=150), nullable=False),
    sa.Column('patient_phone', sa.String(length=30), nullable=False),
    sa.Column('emergency_type', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'COMPLETED', 'CANCELLED', name='emergencystatus'), nullable=False),
    sa.Column('selected_ambulance_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['selected_ambulance_id'], ['ambulances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_emergency_type'), ['emergency_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_patient_phone'), ['patient_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_user_id'), ['user_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ambulance_id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_updated_at'), ['updated_at'], unique=False)

    op.create_table('call_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('driver_phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('call_initiated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emergency_request_id'], ['emergency_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_records_ambulance_id'), ['ambulance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_call_initiated_at'), ['call_initiated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_emergency_request_id'), ['emergency_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_emergency_request_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_call_initiated_at'))
        batch_op.drop_index(batch_op.f('ix_call_records_ambulance_id'))

    op.drop_table('call_records')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_locations_longitude'))
        batch_op.drop_index(batch_op.f('ix_locations_latitude'))
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    op.drop_table('locations')
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_patient_phone'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_emergency_type'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_created_at'))

    op.drop_table('emergency_requests')
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availabilities_is_online'))
        batch_op.drop_index(batch_op.f('ix_availabilities_id'))

    op.drop_table('availabilities')
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambulances_verification_status'))
        batch_op.drop_index(batch_op.f('ix_ambulances_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_ambulances_id'))
        batch_op.drop_index(batch_op.f('ix_ambulances_ambulance_type'))

    op.drop_table('ambulances')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_license_number'))
        batch_op.drop_index(batch_op.f('ix_drivers_is_verified'))
        batch_op.drop_index(batch_op.f('ix_drivers_id'))

    op.drop_table('drivers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
